-- Clear existing problem statements and insert new ones
-- This script updates the problem statements with real department-specific content

-- First, update the department constraint to include the new department codes
ALTER TABLE problem_statements DROP CONSTRAINT IF EXISTS problem_statements_department_check;
ALTER TABLE problem_statements ADD CONSTRAINT problem_statements_department_check 
CHECK (department IN ('CSE', 'AIDS', 'ECE', 'EEE', 'MECH'));

-- Clear existing problem statements
DELETE FROM problem_statements;

-- Reset the sequence for clean IDs
ALTER SEQUENCE problem_statements_id_seq RESTART WITH 1;

-- Insert comprehensive real problem statements
INSERT INTO problem_statements (title, description, department, max_teams) VALUES
-- CSE (Computer Applications / Computer Science)
('Smart Campus Management System', 'Inefficient campus operations due to fragmented and manual management systems. To build a centralized digital platform that automates academic, administrative, and infrastructure operations. To improve transparency, efficiency, and decision-making using real-time analytics. Colleges handle multiple operations such as attendance, scheduling, security, and resource usage, often through isolated systems. This leads to redundancy, data inconsistency, and delays. A smart campus platform can integrate all subsystems into one intelligent solution. It enables automation, analytics, and better user experience for students and staff.', 'CSE', 3),
('AI-Based Student Performance Prediction System', 'Lack of early prediction systems for identifying academically at-risk students. To develop an AI model that predicts student performance using academic and behavioral data. To enable timely academic counseling and intervention strategies. Many students struggle academically due to undetected learning gaps and personal challenges. Traditional grading methods do not provide predictive insights. An AI-based system can analyze attendance, test scores, and learning patterns to forecast performance. This allows educators to take preventive action and improve learning outcomes.', 'CSE', 3),
('Cyber Threat Detection & Prevention Platform', 'Institutional networks are vulnerable to cyberattacks due to insufficient real-time monitoring. To build an AI-based intrusion detection system that identifies cyber threats in real time. To strengthen network security through predictive threat analysis and alerts. Educational and enterprise networks face increasing risks from malware, phishing, and unauthorized access. Traditional security systems rely on static rules and manual analysis. An intelligent platform can analyze traffic patterns and identify anomalies instantly. This improves detection accuracy and reduces response time.', 'CSE', 3),
('Real-Time Traffic Management System', 'Traffic congestion occurs due to inefficient signal timing and lack of live traffic analysis. To design an IoT-enabled traffic monitoring and signal optimization system. To reduce congestion, travel time, and fuel wastage. Urban traffic systems operate mostly on fixed timing mechanisms that fail to adapt to changing road conditions. Real-time traffic data collection using sensors can improve signal control decisions. Cloud-based analytics can optimize flow dynamically. This leads to smoother traffic movement and reduced environmental impact.', 'CSE', 3),
('Secure Online Examination Platform', 'Online examinations face integrity issues such as cheating and impersonation. To develop a secure online exam system integrated with AI-based proctoring. To ensure exam fairness, authenticity, and transparency. With the rise of online education, examination integrity has become a major concern. Manual monitoring is unreliable and inefficient. AI-based face recognition, activity tracking, and behavior analysis can prevent malpractices. A secure platform improves trust and evaluation accuracy.', 'CSE', 3),
('Digital Complaint & Grievance Redressal System', 'Manual complaint handling leads to slow resolution and lack of transparency. To build a digital platform for registering, tracking, and resolving grievances. To improve accountability and response efficiency. Students and staff often struggle to get timely responses for institutional issues. Paper-based complaint systems lack tracking and prioritization. A digital grievance platform enables real-time tracking, escalation, and analytics. This ensures faster resolutions and improved institutional management.', 'CSE', 3),
('Cloud-Based Hostel & Mess Management System', 'Manual hostel and mess operations cause inefficiency and billing disputes. To design a cloud-based automation platform for hostel and mess management. To improve operational efficiency, transparency, and record accuracy. Managing hostel rooms, food services, attendance, and billing manually leads to errors and delays. A cloud-based system can centralize operations and provide real-time updates. Automated workflows improve service quality and reduce administrative burden. It also enhances student satisfaction.', 'CSE', 3),
('Blockchain-Based Certificate Verification System', 'Academic certificate forgery is increasing due to insecure verification systems. To develop a blockchain-based platform for secure credential storage and validation. To ensure tamper-proof and transparent verification processes. Fake certificates damage institutional credibility and recruitment reliability. Centralized databases are prone to manipulation and breaches. Blockchain provides immutable and decentralized record storage. This guarantees authenticity and instant verification of academic credentials.', 'CSE', 3),
('Smart Waste Collection & Route Optimization System', 'Inefficient waste collection leads to fuel wastage and environmental pollution. To develop an IoT-based smart waste monitoring and route optimization platform. To improve collection efficiency and reduce operational costs. Conventional waste collection systems follow fixed schedules without considering actual bin status. IoT sensors can detect fill levels in real time. Optimized routing reduces fuel usage and operational delays. This ensures cleaner and smarter urban waste management.', 'CSE', 3),
('AI-Based College Information Chatbot', 'Manual enquiry systems cause delays in accessing institutional information. To build an AI chatbot that provides instant responses to student queries. To improve accessibility and reduce administrative workload. Students frequently seek information related to academics, admissions, and administration. Manual response systems are slow and inefficient. AI chatbots can provide 24/7 automated support. This improves communication efficiency and student experience.', 'CSE', 3),

-- AIDS (Artificial Intelligence & Data Science)
('AI-Based Disease Detection System', 'Delayed and inaccurate disease diagnosis due to dependence on manual medical image analysis. To build a deep learning model that detects diseases from medical images with high accuracy. To assist doctors in early diagnosis and faster treatment planning. Medical imaging plays a crucial role in disease diagnosis, but manual analysis is time-consuming and error-prone. AI-based systems can analyze X-rays, CT scans, and MRIs with high precision. Automated detection improves diagnosis speed and accuracy. This system supports healthcare professionals in clinical decision-making.', 'AIDS', 3),
('Intelligent Crop Yield Prediction System', 'Farmers lack accurate tools to predict crop yield under changing environmental conditions. To design a machine learning model that predicts crop yield using soil and climate data. To help farmers improve planning, productivity, and profitability. Crop yield depends on multiple factors such as rainfall, soil type, temperature, and fertilizer usage. Traditional prediction methods are unreliable. AI models can analyze historical and real-time data to generate accurate yield forecasts. This improves agricultural planning and reduces financial risk.', 'AIDS', 3),
('Fake News Detection System using NLP', 'Rapid spread of fake news leads to misinformation and social instability. To build an NLP-based system that identifies fake and misleading news content. To improve information reliability on digital platforms. Social media platforms allow fast sharing of unverified information. Manual verification is impossible at scale. NLP-based models can analyze linguistic patterns and semantics to detect fake news. This helps reduce misinformation and protect public trust.', 'AIDS', 3),
('AI-Based Resume Screening System', 'Manual resume screening is slow, inefficient, and biased. To develop an AI-driven resume screening platform for candidate ranking. To speed up recruitment and improve candidate-job matching accuracy. Recruiters manually review hundreds of resumes, leading to delays and inconsistent selection. AI models can analyze resume content and job descriptions to rank candidates automatically. This improves hiring efficiency and fairness. It also reduces operational cost.', 'AIDS', 3),
('Smart Surveillance System using AI Vision', 'Traditional surveillance requires continuous human monitoring, leading to inefficiencies. To build an AI-powered system that detects suspicious activities automatically. To improve public safety and security monitoring. Conventional CCTV systems generate huge amounts of video data that require human supervision. AI-based vision systems can analyze video feeds in real time. They can detect abnormal behavior, unauthorized access, and potential threats. This enhances proactive security.', 'AIDS', 3),
('Financial Fraud Detection System', 'Rising online transactions increase financial fraud risks. To design an AI model that detects fraudulent transactions in real time. To minimize financial losses and enhance transaction security. Digital payments have grown rapidly, making fraud detection critical. Traditional rule-based systems fail to detect complex fraud patterns. Machine learning algorithms can analyze transaction behavior and identify anomalies. This improves fraud prevention efficiency.', 'AIDS', 3),
('Predictive Analytics for Student Dropout Risk', 'Institutions fail to identify early indicators of student dropout. To develop predictive models that identify students at risk of dropping out. To enable early academic and emotional intervention strategies. Student dropout affects academic outcomes and institutional reputation. Multiple factors contribute to dropout, including performance, attendance, and mental health. AI models can analyze these patterns to predict risks early. This supports timely intervention.', 'AIDS', 3),
('Deepfake Detection System', 'Manipulated videos and images spread misinformation and harm reputations. To develop an AI-based deepfake detection platform. To ensure authenticity and trust in digital media. Advancements in AI have made it easy to create realistic fake media. Detecting such manipulation is challenging. Deep learning models can analyze facial inconsistencies, motion artifacts, and pixel patterns. This helps combat digital misinformation.', 'AIDS', 3),
('Air Quality Prediction System', 'Air pollution fluctuations pose serious health and environmental risks. To build a predictive model that forecasts air quality levels. To assist public health agencies in preventive planning. Air quality is influenced by industrial emissions, traffic, and weather patterns. Accurate prediction is essential for public safety. AI models can analyze historical pollution and climate data. This enables early alerts and health protection measures.', 'AIDS', 3),
('Personalized Learning Recommendation System', 'Uniform teaching methods fail to address individual student learning needs. To design an AI-based adaptive learning platform. To personalize educational content based on student performance. Students learn at different speeds and styles. Traditional education systems lack personalization. AI systems can track performance and learning behavior. This enables customized learning paths and improved academic success.', 'AIDS', 3),

-- ECE (Electronics & Communication Engineering)
('IoT-Based Smart Home Automation System', 'Manual appliance control causes inconvenience and inefficient energy usage. To build an IoT-based smart home system for remote monitoring and automation. To enhance comfort, safety, and energy efficiency. Traditional homes rely on manual switching and monitoring. IoT-enabled devices allow centralized control of appliances. Sensors and automation reduce energy wastage. This improves user convenience and safety.', 'ECE', 3),
('Intelligent Traffic Signal Control System', 'Fixed-timer traffic signals cause unnecessary congestion. To design a sensor-based adaptive traffic signal system. To reduce traffic congestion and waiting time. Traditional traffic lights operate on predefined schedules. Real-time vehicle density varies significantly. Sensors can measure traffic flow and dynamically control signal timing. This improves traffic efficiency and safety.', 'ECE', 3),
('Real-Time Air Quality Monitoring System', 'Lack of continuous pollution monitoring leads to delayed response. To develop an IoT-based system for real-time air quality monitoring. To provide timely pollution alerts. Air pollution varies throughout the day and location. Manual sampling fails to capture real-time changes. IoT sensors can continuously collect pollution data. This supports immediate health warnings and policy decisions.', 'ECE', 3),
('Smart Irrigation System', 'Manual irrigation leads to water wastage and crop stress. To design an automated irrigation system using soil and climate sensors. To optimize water usage and improve crop yield. Agriculture consumes large amounts of water. Inefficient irrigation results in wastage and reduced productivity. Sensor-based automation ensures water is supplied only when needed. This supports sustainable agriculture.', 'ECE', 3),
('Automatic Railway Gate Control System', 'Manual railway gate operations cause accidents and traffic delays. To build an automated gate control system using train detection sensors. To improve safety and reduce human error. Accidents at railway crossings are often due to delayed gate closure. Sensors can detect approaching trains and automatically operate gates. This enhances safety and reduces congestion.', 'ECE', 3),
('IoT-Based Smart Parking System', 'Drivers waste time and fuel searching for parking spaces. To develop a real-time parking availability detection system. To reduce traffic congestion and fuel consumption. Urban parking is a major challenge. IoT sensors can monitor slot occupancy. Real-time guidance helps drivers find parking quickly. This reduces emissions and traffic buildup.', 'ECE', 3),
('Wearable Health Monitoring Device', 'Continuous health monitoring is difficult without portable systems. To design a wearable device that tracks vital health parameters. To enable early detection of medical abnormalities. Vital signs such as heart rate and oxygen levels are crucial health indicators. Wearable sensors enable continuous monitoring. Data analytics can detect early warning signs. This improves preventive healthcare.', 'ECE', 3),
('Smart Blind Stick for Visually Impaired', 'Visually impaired individuals face difficulty in safe navigation. To build a sensor-based smart stick for obstacle detection. To improve independent mobility and safety. Blind individuals rely on basic sticks that cannot detect obstacles effectively. Ultrasonic and IR sensors can detect nearby objects. Alerts through vibration or audio improve navigation safety. This enhances independence.', 'ECE', 3),
('Flood Detection & Early Warning System', 'Late flood warnings result in heavy property damage and loss of life. To develop an IoT-based flood monitoring and alert system. To provide early warnings for disaster preparedness. Water level monitoring in rivers and dams is crucial for flood prediction. IoT sensors can provide real-time data. Automated alerts help authorities take early action. This reduces disaster impact.', 'ECE', 3),
('Smart Street Lighting System', 'Traditional street lights consume excessive energy. To design an automated lighting system using motion and light sensors. To reduce energy consumption and maintenance cost. Street lights operate continuously regardless of activity. Sensors can control brightness based on movement and ambient light. This saves energy and extends lamp life. It supports sustainable urban development.', 'ECE', 3),

-- EEE (Electrical & Electronics Engineering)
('Smart Energy Meter with Mobile Monitoring', 'Traditional energy meters provide limited insights into real-time power consumption. To design a smart energy meter with mobile connectivity for real-time monitoring. To promote efficient electricity usage and energy conservation. Conventional meters only display cumulative readings, offering no real-time consumption data. Smart meters with IoT connectivity allow users to track usage patterns instantly. This enables better energy management and cost reduction. Utilities also benefit from automated billing and monitoring.', 'EEE', 3),
('Solar Power Optimization System using AI', 'Solar energy systems operate inefficiently due to improper panel orientation and load management. To develop an AI-based optimization system to maximize solar energy generation. To improve renewable energy utilization and reduce power losses. Solar panel efficiency depends on orientation, temperature, and load demand. AI algorithms can analyze environmental conditions and optimize panel positioning and power flow. This increases energy output and system reliability. It supports sustainable energy development.', 'EEE', 3),
('Smart Grid Fault Detection System', 'Delayed fault detection in power grids leads to outages and equipment damage. To build a real-time fault detection and monitoring system for smart grids. To improve grid reliability and response time. Power grid faults disrupt supply and damage infrastructure. Traditional systems rely on manual inspections and delayed reports. Sensor-based monitoring combined with analytics enables fast fault detection. This enhances grid stability and maintenance efficiency.', 'EEE', 3),
('EV Charging Station Management System', 'Unorganized EV charging infrastructure causes long waiting times and inefficient energy distribution. To develop an intelligent EV charging management platform. To optimize charging schedules and energy utilization. With increasing electric vehicle adoption, charging stations face congestion. Smart scheduling and load management systems improve charging efficiency. Real-time data enables dynamic power distribution. This supports sustainable transportation growth.', 'EEE', 3),
('Power Theft Detection System using Machine Learning', 'Power theft causes significant financial losses and grid instability. To design an ML-based system to detect abnormal power usage patterns. To reduce electricity theft and improve revenue protection. Unauthorized power usage disrupts energy distribution and causes losses. Traditional detection methods are slow and inaccurate. Machine learning models can analyze consumption data to identify anomalies. This enables early detection and preventive action.', 'EEE', 3),
('Automatic Power Factor Correction System', 'Low power factor results in energy loss and increased electricity bills. To build an automatic system that maintains optimal power factor levels. To improve power efficiency and reduce energy costs. Poor power factor increases transmission losses and voltage drops. Automated correction using capacitor banks improves system efficiency. Real-time monitoring enables dynamic adjustment. This leads to better power quality.', 'EEE', 3),
('Energy Consumption Prediction & Optimization System', 'Unplanned power consumption leads to inefficient load management. To develop predictive analytics models for energy demand forecasting. To optimize load distribution and reduce peak demand stress. Energy demand fluctuates based on time, weather, and usage patterns. Predictive models can forecast consumption trends. This enables effective load planning and energy conservation. It also reduces grid overload risks.', 'EEE', 3),
('Smart Street Light Power Optimization System', 'High power consumption in public lighting systems increases operational costs. To design intelligent lighting control systems for energy optimization. To reduce power usage while maintaining safety standards. Public lighting systems operate continuously without dynamic control. Smart sensors adjust brightness based on movement and ambient light. This saves electricity and extends lamp lifespan. It supports smart city development.', 'EEE', 3),
('Renewable Energy Monitoring System', 'Renewable energy systems lack real-time performance monitoring. To develop a monitoring platform for solar and wind power plants. To enhance efficiency and system reliability. Renewable sources are variable in nature. Continuous monitoring helps optimize performance. Sensor data combined with analytics improves power output prediction. This ensures better renewable energy management.', 'EEE', 3),
('Battery Health Monitoring System for EVs', 'Battery degradation reduces electric vehicle performance and lifespan. To design a battery health monitoring system for early fault detection. To extend battery life and improve EV reliability. EV batteries degrade due to thermal stress and repeated charging cycles. Monitoring voltage, temperature, and charging patterns helps predict failures. This improves safety and maintenance planning. It also reduces operational cost.', 'EEE', 3),

-- MECH (Mechanical Engineering)
('Automated Waste Segregation Machine', 'Manual waste segregation is inefficient, unhygienic, and inaccurate. To design an automated machine that segregates waste based on material type. To improve recycling efficiency and waste management quality. Waste segregation is crucial for recycling and environmental safety. Manual sorting is slow and unsafe. Automated mechanical systems using sensors and actuators can efficiently separate materials. This improves recycling output and hygiene.', 'MECH', 3),
('Smart Vehicle Accident Detection System', 'Delayed accident detection results in slow emergency response. To develop a sensor-based accident detection and alert system. To enable rapid emergency assistance and reduce fatalities. Road accidents require immediate medical attention. Sensor-based systems can detect sudden impact and abnormal motion. Automated alerts with location tracking reduce emergency response time. This saves lives.', 'MECH', 3),
('Robotic Arm for Industrial Material Handling', 'Manual material handling reduces productivity and increases injury risk. To design a robotic arm for automated industrial material handling. To improve productivity and workplace safety. Industries require repetitive lifting and placement tasks. Manual handling is inefficient and unsafe. Robotic arms can perform precise movements with consistency. This improves production speed and reduces human effort.', 'MECH', 3),
('Energy Efficient Refrigeration System', 'Conventional refrigeration systems consume excessive electrical energy. To design a refrigeration system with improved energy efficiency. To reduce power consumption and environmental impact. Refrigeration is widely used in domestic and industrial applications. Traditional systems have low efficiency and high power usage. Improved thermal design and compressor control enhance efficiency. This reduces operational cost and emissions.', 'MECH', 3),
('Automated Smart Water Pumping System', 'Manual water pumping leads to water wastage and energy loss. To design an automated pumping system based on water demand. To improve water conservation and energy efficiency. Water distribution systems often operate inefficiently due to manual control. Automated systems regulate flow based on tank levels and usage demand. This reduces wastage and optimizes energy use. It supports sustainable water management.', 'MECH', 3),
('Solar-Powered Agricultural Machine', 'Fuel-powered agricultural machines increase cost and pollution. To design a solar-powered multi-purpose farming machine. To reduce operational cost and environmental impact. Agriculture depends heavily on fossil-fuel machinery. Solar-powered alternatives reduce emissions and fuel expenses. Mechanical design integrated with renewable energy supports sustainable farming. This improves productivity and environmental health.', 'MECH', 3),
('Smart Helmet with Safety Monitoring', 'Lack of helmet compliance leads to severe head injuries in accidents. To design a smart helmet that monitors usage and safety parameters. To improve rider safety and accident response. Helmet non-compliance is a major cause of fatalities. Smart helmets detect wearing status, impact, and rider condition. Alerts improve emergency response. This promotes safer riding practices.', 'MECH', 3),
('Automated Car Parking System', 'Urban parking inefficiency causes congestion and space wastage. To design an automated mechanical parking system. To optimize space utilization and reduce parking time. Traditional parking requires large space and manual control. Automated parking mechanisms improve vertical and horizontal space usage. Mechanical automation increases efficiency. This supports smart urban infrastructure.', 'MECH', 3),
('Portable Low-Cost Sanitation System', 'Many regions lack access to hygienic sanitation facilities. To design a portable, affordable sanitation unit. To improve hygiene and public health standards. Sanitation access is limited in rural and disaster-affected areas. Portable systems provide immediate hygiene solutions. Mechanical design ensures durability and low cost. This improves health and living conditions.', 'MECH', 3),
('Fuel Efficiency Optimization System', 'Low fuel efficiency increases transportation costs and emissions. To develop mechanical optimization techniques to improve vehicle mileage. To reduce fuel consumption and environmental impact. Fuel efficiency depends on engine design, driving conditions, and mechanical parameters. Optimized mechanical systems reduce friction and improve combustion efficiency. This results in better mileage and lower emissions. It supports sustainable transportation.', 'MECH', 3);

-- Show the result
SELECT 'Problem statements updated successfully! Total statements: ' || COUNT(*) FROM problem_statements;