-- Migration: Add CIVIL and MBA Problem Statements
-- Date: 2026-02-16
-- Description: Adds 10 problem statements each for Civil Engineering and MBA programs

-- Insert CIVIL Engineering problem statements (only if they don't already exist)
INSERT INTO problem_statements (title, description, department, max_teams)
SELECT * FROM (VALUES
('Smart Water Management System', 'Inefficient water distribution and monitoring lead to large-scale water wastage. To design a smart system for real-time water usage monitoring and leakage detection. To optimize water distribution and promote conservation. Urban water supply systems suffer from leaks, uneven distribution, and poor monitoring. Smart sensors and data analytics can track flow and detect losses. Automated control improves supply efficiency. This supports sustainable water resource management.', 'CIVIL', 3),
('AI-Based Structural Health Monitoring System', 'Lack of continuous monitoring leads to late detection of structural damage. To develop a sensor-based system for real-time structural health monitoring. To predict failures and improve safety and maintenance planning. Buildings and bridges undergo stress due to load, vibration, and environmental conditions. Traditional inspection methods are periodic and manual. Sensor-based monitoring with analytics enables early detection of damage. This improves structural safety and lifespan.', 'CIVIL', 3),
('Smart Traffic & Road Condition Monitoring System', 'Poor road monitoring leads to accidents and inefficient maintenance. To develop an intelligent road monitoring platform using sensors and data analytics. To improve traffic safety and road maintenance planning. Road surface degradation and traffic congestion impact transportation efficiency. IoT sensors and camera systems can collect real-time road condition data. Analytics help authorities schedule timely repairs. This enhances road safety and travel comfort.', 'CIVIL', 3),
('Sustainable Smart Building Design System', 'Traditional buildings consume excessive energy and natural resources. To design sustainable building models that minimize energy and water consumption. To promote green construction and environmental conservation. Buildings contribute significantly to energy usage and carbon emissions. Smart building designs integrate energy-efficient materials, natural lighting, and ventilation. Sustainable design improves occupant comfort and reduces operational cost. This supports eco-friendly infrastructure.', 'CIVIL', 3),
('Automated Construction Site Safety Monitoring System', 'Construction site accidents occur due to lack of real-time safety monitoring. To develop an automated safety monitoring system using sensors and computer vision. To reduce workplace accidents and improve labor safety. Construction environments are hazardous and require continuous supervision. Wearable sensors and cameras can monitor worker movements and equipment operations. Real-time alerts prevent unsafe actions. This improves occupational safety standards.', 'CIVIL', 3),
('Smart Rainwater Harvesting System', 'Rainwater is poorly utilized, leading to groundwater depletion. To design an intelligent rainwater harvesting and storage management system. To enhance groundwater recharge and reduce water scarcity. Large amounts of rainwater runoff go unused. Smart harvesting systems capture, filter, and store rainwater efficiently. Sensors regulate storage and usage. This promotes sustainable water conservation practices.', 'CIVIL', 3),
('Intelligent Wastewater Treatment Monitoring System', 'Inefficient wastewater treatment causes environmental pollution. To develop a monitoring system for real-time wastewater treatment analysis. To ensure effective purification and regulatory compliance. Wastewater treatment plants require continuous parameter monitoring. IoT sensors track pH, turbidity, and chemical content. Data analytics improves treatment efficiency. This protects water bodies and public health.', 'CIVIL', 3),
('Smart Urban Flood Management System', 'Urban flooding causes property damage and traffic disruption. To design a real-time flood monitoring and drainage control system. To improve disaster preparedness and response. Urban drainage systems struggle during heavy rainfall. Sensor-based monitoring detects rising water levels. Automated alerts and drainage control reduce flooding risks. This improves urban resilience.', 'CIVIL', 3),
('Sustainable Low-Cost Housing Design', 'Affordable housing projects often compromise on quality and sustainability. To design low-cost, durable, and eco-friendly housing models. To improve living standards for economically weaker communities. Housing shortages demand innovative low-cost construction techniques. Sustainable materials and modular designs reduce cost and construction time. Energy-efficient layouts enhance comfort. This supports inclusive urban development.', 'CIVIL', 3),
('Smart Concrete Quality Monitoring System', 'Concrete quality inconsistencies lead to reduced structural strength. To develop a sensor-based system to monitor concrete curing and strength gain. To improve construction quality and durability. Concrete performance depends on curing conditions and mix quality. Embedded sensors can monitor temperature and moisture. Data analysis predicts strength development. This ensures reliable and high-quality construction.', 'CIVIL', 3)
) AS v(title, description, department, max_teams)
WHERE NOT EXISTS (
    SELECT 1 FROM problem_statements WHERE problem_statements.title = v.title
);

-- Insert MBA problem statements (only if they don't already exist)
INSERT INTO problem_statements (title, description, department, max_teams)
SELECT * FROM (VALUES
('Digital Marketing Strategy Optimization Platform', 'Businesses struggle to design effective digital marketing strategies due to poor data utilization. To develop a data-driven digital marketing optimization system. To improve customer engagement, reach, and conversion rates. Companies invest heavily in digital marketing but lack analytical insights. A smart platform can analyze campaign performance, customer behavior, and engagement metrics. It can suggest optimized strategies. This leads to higher ROI and better market positioning.', 'MBA', 3),
('Customer Relationship Management (CRM) Analytics System', 'Organizations fail to retain customers due to lack of personalized engagement strategies. To build an intelligent CRM system using data analytics. To enhance customer satisfaction, loyalty, and retention. Customer churn negatively impacts profitability. CRM analytics can identify customer preferences, behavior, and pain points. Personalized engagement strategies improve customer relationships. This results in long-term business growth.', 'MBA', 3),
('Supply Chain Demand Forecasting System', 'Inaccurate demand forecasting causes inventory shortages and excess stock. To design a predictive system for accurate demand forecasting. To optimize inventory planning and reduce operational costs. Supply chain inefficiencies arise due to unpredictable demand patterns. Data-driven forecasting models improve demand estimation accuracy. This helps businesses maintain optimal inventory levels. It reduces storage costs and prevents stockouts.', 'MBA', 3),
('Financial Risk Assessment & Investment Decision Platform', 'Investment decisions are often made without accurate risk evaluation. To develop a financial analytics system for risk assessment and investment planning. To improve decision quality and reduce financial uncertainty. Financial markets involve uncertainty and volatility. Data analytics tools can evaluate historical trends and risk indicators. This supports better investment strategies. It improves portfolio performance and capital protection.', 'MBA', 3),
('Employee Performance Evaluation & HR Analytics System', 'Traditional performance appraisal systems lack objectivity and real-time insights. To build an HR analytics platform for performance tracking and workforce planning. To enhance employee productivity and organizational efficiency. Manual employee evaluations are time-consuming and subjective. HR analytics enables continuous performance monitoring. Data-driven insights support fair evaluations and training planning. This improves employee engagement and output.', 'MBA', 3),
('Startup Business Planning & Feasibility Analysis Tool', 'Many startups fail due to poor market analysis and planning. To design a business feasibility and strategy planning platform. To support informed entrepreneurial decision-making. Entrepreneurs require market insights, cost analysis, and risk assessment. A digital planning tool can simulate business scenarios. This helps evaluate feasibility and profitability. It reduces startup failure rates.', 'MBA', 3),
('Customer Churn Prediction & Retention Strategy System', 'Businesses lose customers without identifying early warning signs. To develop a predictive model for customer churn analysis. To implement targeted customer retention strategies. Customer churn reduces revenue and brand loyalty. Predictive analytics can detect dissatisfaction patterns. Early intervention strategies improve customer experience. This ensures business sustainability.', 'MBA', 3),
('Smart Inventory Management & Cost Optimization System', 'Poor inventory planning leads to increased operational cost and wastage. To develop an intelligent inventory tracking and optimization platform. To minimize storage cost and prevent stock losses. Businesses often maintain excess inventory to avoid shortages. Smart systems analyze demand patterns and supply cycles. Automated alerts improve restocking efficiency. This enhances financial performance.', 'MBA', 3),
('Business Intelligence Dashboard for Strategic Decision-Making', 'Decision-makers lack real-time insights for strategic planning. To develop an interactive business intelligence dashboard. To enable data-driven managerial decision-making. Organizations collect large volumes of data but fail to extract actionable insights. BI dashboards visualize performance metrics. This supports quick and informed decisions. It improves strategic agility and competitiveness.', 'MBA', 3),
('Consumer Behavior Analysis & Market Trend Prediction System', 'Businesses struggle to predict changing customer preferences and market trends. To build a consumer behavior analytics and trend prediction platform. To improve product planning and marketing strategies. Customer preferences change rapidly in competitive markets. Data analytics can identify emerging trends and buying patterns. Predictive insights support proactive business planning. This enhances market success.', 'MBA', 3)
) AS v(title, description, department, max_teams)
WHERE NOT EXISTS (
    SELECT 1 FROM problem_statements WHERE problem_statements.title = v.title
);
